const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"床位信息管理",
                        "menuJump":"列表",
                        "tableName":"chuangwei"
                    },
					{
					    "buttons":[
					        "查看",
					        "审核",
					        "删除"
					    ],
					    "menu":"床位申请管理",
					    "menuJump":"列表",
					    "tableName":"chaungweishenqing"
					}
                ],
                "menu":"床位信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"缴费类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryFeiyongxinxi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"项目类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryLiliaoxiangmu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"公告类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryNews"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"请假类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryQingjia"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"费用信息管理",
                        "menuJump":"列表",
                        "tableName":"feiyongxinxi"
                    }
                ],
                "menu":"费用信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"理疗项目管理",
                        "menuJump":"列表",
                        "tableName":"liliaoxiangmu"
                    }
                ],
                "menu":"理疗项目管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"意见反馈管理",
                        "menuJump":"列表",
                        "tableName":"liuyan"
                    }
                ],
                "menu":"意见反馈管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告信息管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"公告信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "审核",
                            "删除"
                        ],
                        "menu":"项目申请管理",
                        "menuJump":"列表",
                        "tableName":"xiangmushenqing"
                    }
                ],
                "menu":"项目申请管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"患者请假管理",
                        "menuJump":"列表",
                        "tableName":"xueshengqingjia"
                    }
                ],
                "menu":"患者请假管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"医生管理",
                        "menuJump":"列表",
                        "tableName":"yisheng"
                    }
                ],
                "menu":"医生管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "审核",
                            "删除"
                        ],
                        "menu":"医生请假管理",
                        "menuJump":"列表",
                        "tableName":"yishengqingjia"
                    }
                ],
                "menu":"医生请假管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"患者管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"患者管理"
            }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "删除"
	                    ],
	                    "menu":"医嘱管理",
	                    "menuJump":"列表",
	                    "tableName":"yizhu"
	                }
	            ],
	            "menu":"医嘱管理"
	        }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                    ],
	                    "menu":"床位信息管理",
	                    "menuJump":"列表",
	                    "tableName":"chuangwei"
	                },
					{
					    "buttons":[
					        "查看",
							"新增",
					        "删除"
					    ],
					    "menu":"床位申请管理",
					    "menuJump":"列表",
					    "tableName":"chaungweishenqing"
					}
	            ],
	            "menu":"床位信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增"
	                    ],
	                    "menu":"费用信息管理",
	                    "menuJump":"列表",
	                    "tableName":"feiyongxinxi"
	                }
	            ],
	            "menu":"费用信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                    ],
	                    "menu":"理疗项目管理",
	                    "menuJump":"列表",
	                    "tableName":"liliaoxiangmu"
	                }
	            ],
	            "menu":"理疗项目管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告信息管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "审核"
	                    ],
	                    "menu":"项目申请管理",
	                    "menuJump":"列表",
	                    "tableName":"xiangmushenqing"
	                }
	            ],
	            "menu":"项目申请管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
							"审核",
	                        "删除"
	                    ],
	                    "menu":"患者请假管理",
	                    "menuJump":"列表",
	                    "tableName":"xueshengqingjia"
	                }
	            ],
	            "menu":"患者请假管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
							"新增",
	                        "删除"
	                    ],
	                    "menu":"我的请假记录",
	                    "menuJump":"列表",
	                    "tableName":"yishengqingjia"
	                }
	            ],
	            "menu":"我的请假记录"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
							"新增",
							"修改",
	                        "删除"
	                    ],
	                    "menu":"患者管理",
	                    "menuJump":"列表",
	                    "tableName":"yonghu"
	                }
	            ],
	            "menu":"患者管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
							"新增",
							"修改",
	                        "删除"
	                    ],
	                    "menu":"医嘱管理",
	                    "menuJump":"列表",
	                    "tableName":"yizhu"
	                }
	            ],
	            "menu":"医嘱管理"
	        }
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"医生",
	    "tableName":"yisheng"
	},
	{
	    "backMenu":[
	        {
	            "child":[
					{
					    "buttons":[
					        "查看"
					    ],
					    "menu":"床位申请信息",
					    "menuJump":"列表",
					    "tableName":"chaungweishenqing"
					}
	            ],
	            "menu":"床位信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"费用信息管理",
	                    "menuJump":"列表",
	                    "tableName":"feiyongxinxi"
	                }
	            ],
	            "menu":"费用信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"理疗项目管理",
	                    "menuJump":"列表",
	                    "tableName":"liliaoxiangmu"
	                },
					{
					    "buttons":[
					        "查看",
					        "新增",
					        "删除"
					    ],
					    "menu":"项目申请管理",
					    "menuJump":"列表",
					    "tableName":"xiangmushenqing"
					}
	            ],
	            "menu":"理疗项目管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "删除"
	                    ],
	                    "menu":"意见反馈管理",
	                    "menuJump":"列表",
	                    "tableName":"liuyan"
	                }
	            ],
	            "menu":"意见反馈管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告信息管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告信息管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "删除"
	                    ],
	                    "menu":"我的请假记录",
	                    "menuJump":"列表",
	                    "tableName":"xueshengqingjia"
	                }
	            ],
	            "menu":"我的请假记录"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"医嘱管理",
	                    "menuJump":"列表",
	                    "tableName":"yizhu"
	                }
	            ],
	            "menu":"医嘱管理"
	        }
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"患者",
	    "tableName":"yonghu"
	}
]
    }
}
export default menu;
